// // import Head from 'next/head'
// // import Image from 'next/image'
// // import styles from '../styles/Home.module.css'
// // import Link from 'next/link'
// import {DBHandler} from "../dbhandler/dbhandler";
//
// // TODO: add handlers and let fields here
// let var1 = false;
// let var2 = false;
// let var3 = 3;
// let object: object;
// let dbHandler = new DBHandler();
//
// // sample handler
// // TODO: figure out async issues in handler
// function handler1(event: Event) {
//     // var3 = event.target;
//     // object = await dbHandler.query1(var3);
//     writeOutToTable(object)
// }
//
// // TODO: write this function
// // parse and output table
// function writeOutToTable(object: Object) {
//
// }
//
// // TODO: put onClick here
// // TODO: create table
//
// export default function Home() {
//     return (
//         <div className={styles.container}>
//             <Head>
//                 <title>Create Next App</title>
//                 <meta name="description" content="Generated by create next app" />
//                 <link rel="icon" href="/favicon.ico" />
//             </Head>
//
//             <main className={styles.main}>
//                 <div className={styles.grid}>
//                     <h1> User </h1>
//                 </div>
//                 <br/>
//                 <h2> URL:  </h2>
//                 {/*<input id="url" type="checkbox" onChange={handler1}/>*/}
//                 <input id="url" type="checkbox" />
//
//                 <br/>
//
//                 <h2> Position Type: </h2>
//                 <input id="url" type="checkbox"/>
//                 <br/>
//
//                 <Link href = "/">
//                     <a> Back to home </a>
//                 </Link>
//             </main>
//
//             <footer className={styles.footer}>
//                 <a
//                     href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//                     target="_blank"
//                     rel="noopener noreferrer"
//                 >
//                     Powered by{' '}
//                     <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//                 </a>
//             </footer>
//         </div>
//     )
// }
